apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p2b2md89j-dotnet-basic
  janus-idp.io/tekton: p2b2md89j-dotnet-basic
  backstage.io/kubernetes-id: p2b2md89j-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p2b2md89j-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
